language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
 - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false
